## 파이썬 엑셀 라이브러리

+ openpyx
+ pyexcel
+ xlsxwriter
+ xlrd
+ xlwt
+ xlwings : 엑셀 프로그램에 대한 자동화 라이브러리
            다른 라이브러리들은 엑셀 프로그램과 연동되는 것이 아니라 엑셀 파일 포맷을 지원하는 형태인데 반해,
            엑셀을 띄워 놓고 파이썬을 통한 값 가져오기 변경등이 지원
            윈도우/맥 지원
            
            설치> pip install xlwings / conda install xlwings
            Anaconda Python에는 포함되어 있음

In [1]:
# !pip install xlwings
# 여기선 걸리는 부분이 있어서 [Anaconda Prompt]를 관리자 권한으로 실행하여 명령어 실행해야 한다

In [2]:
import xlwings as xw

xw.__version__

'0.17.1'

In [3]:
# 데이타를 바로 엑셀로 보내기
data = [
    ['apple','pear','mango'],
    [100,150, 200],
    [120, 160, 170]
]

In [4]:
# 위의 데이타를 엑셀로 넘김(엑셀 프로그램 작동)

xw.view(data)

### 인터넷 상의 데이타를 엑셀로 보내기

+ 네이버 환율정보 : https://finance.naver.com/marketindex/exchangeList.nhn


1. 데이타를 데이타프레임으로 로딩하기

2. 데이타셋 정보 확인하기

3. 엑셀로 데이타셋 보내기

4. 엑셀에서 데이타 가져오기

In [5]:
# (1) 데이타를 데이타프레임으로 로딩하기

import pandas as pd

url = 'https://finance.naver.com/marketindex/exchangeList.nhn'

df_list = pd.read_html(url)
df=df_list[0] # 전체를 가지고옴, 이중리스트라는 뜻
df

              통화명    매매기준율       현찰                송금           미화환산율
              통화명    매매기준율     사실 때     파실 때    보내실 때    받으실 때  미화환산율
0          미국 USD  1197.30  1218.25  1176.35  1209.00  1185.60  1.000
1        유럽연합 EUR  1348.40  1375.23  1321.57  1361.88  1334.92  1.126
2   일본 JPY (100엔)  1112.68  1132.15  1093.21  1123.58  1101.78  0.929
3          중국 CNY   169.43   177.90   160.96   171.12   167.74  0.142
4          홍콩 HKD   154.49   157.53   151.45   156.03   152.95  0.129
5          대만 TWD    40.64    45.96    37.80     0.00     0.00  0.034
6          영국 GBP  1494.11  1523.54  1464.68  1509.05  1479.17  1.248
7          오만 OMR  3110.03  3386.82  2923.43     0.00     0.00  2.598
8         캐나다 CAD   883.45   900.85   866.05   892.28   874.62  0.738
9         스위스 CHF  1268.19  1293.17  1243.21  1280.87  1255.51  1.059
10        스웨덴 SEK   128.72   131.87   125.57   130.00   127.44  0.108
11         호주 AUD   831.94   848.32   815.56   840.25   823.63  0.695
12       뉴질랜드 NZD   783.33   798.76   767.90   791.16   775.50  0.654
13         체코 CZK    50.55    54.84    46.01    51.10    50.00  0.042
14         칠레 CLP     1.49     1.60     1.38     0.00     0.00  0.001
15         터키 TRY   174.43     0.00     0.00   176.34   172.52  0.146
16         몽골 MNT     0.42     0.00     0.00     0.00     0.00  0.000
17       이스라엘 ILS   348.50   383.35   320.62     0.00     0.00  0.291
18        덴마크 DKK   181.00   185.43   176.57   182.81   179.19  0.151
19       노르웨이 NOK   126.57   129.67   123.47   127.83   125.31  0.106
20    사우디아라비아 SAR   319.19   339.29   297.17   322.38   316.00  0.267
21       쿠웨이트 KWD  3889.86  4142.70  3578.68  3928.75  3850.97  3.249
22        바레인 BHD  3170.82  3373.75  2917.16  3202.52  3139.12  2.648
23     아랍에미리트 AED   325.96   343.88   303.47   329.21   322.71  0.272
24        요르단 JOD  1688.72  1839.01  1553.63     0.00     0.00  1.410
25        이집트 EGP    74.36     0.00     0.00     0.00     0.00  0.062
26         태국 THB    38.46    40.38    36.16    38.84    38.08  0.032
27       싱가포르 SGD   859.36   876.46   842.26   867.95   850.77  0.718
28      말레이시아 MYR   279.58   297.19   258.90     0.00   276.79  0.234
29  인도네시아 IDR 100     8.30     8.88     7.47     8.38     8.22  0.007
30        카타르 QAR   328.84     0.00     0.00     0.00     0.00  0.275
31      카자흐스탄 KZT     2.94     0.00     0.00     0.00     0.00  0.003
32       브루나이 BND   858.28   892.61   806.79     0.00     0.00  0.717
33         인도 INR    16.04     0.00     0.00     0.00     0.00  0.013
34       파키스탄 PKR     7.14     0.00     0.00     0.00     0.00  0.006
35      방글라데시 BDT    14.11     0.00     0.00     0.00     0.00  0.012
36        필리핀 PHP    24.16    26.57    22.18    24.40    23.92  0.020
37        멕시코 MXN    53.51    58.86    49.02    54.04    52.98  0.045
38        브라질 BRL   225.29   248.26   207.27     0.00   222.59  0.188
39    베트남 VND 100     5.16     5.76     4.56     5.21     5.11  0.004
40  남아프리카 공화국 ZAR    70.31    74.52    64.69    71.15    69.47  0.059
41        러시아 RUB    16.78    17.95    14.94    16.94    16.62  0.014
42        헝가리 HUF     3.81     4.16     3.51     3.85     3.77  0.003
43        폴란드 PLN   302.18   326.35   278.01   305.50   298.86  0.252

In [6]:
# (2) 데이타셋 정보 확인하기
# 컬럼명 지정
df.columns=['통화명', '매매기준율','현찰-사실때','현찰-파실때','송금-보낼때','송금-받을때','미화환산율']

df

              통화명    매매기준율   현찰-사실때   현찰-파실때   송금-보낼때   송금-받을때  미화환산율
0          미국 USD  1197.30  1218.25  1176.35  1209.00  1185.60  1.000
1        유럽연합 EUR  1348.40  1375.23  1321.57  1361.88  1334.92  1.126
2   일본 JPY (100엔)  1112.68  1132.15  1093.21  1123.58  1101.78  0.929
3          중국 CNY   169.43   177.90   160.96   171.12   167.74  0.142
4          홍콩 HKD   154.49   157.53   151.45   156.03   152.95  0.129
5          대만 TWD    40.64    45.96    37.80     0.00     0.00  0.034
6          영국 GBP  1494.11  1523.54  1464.68  1509.05  1479.17  1.248
7          오만 OMR  3110.03  3386.82  2923.43     0.00     0.00  2.598
8         캐나다 CAD   883.45   900.85   866.05   892.28   874.62  0.738
9         스위스 CHF  1268.19  1293.17  1243.21  1280.87  1255.51  1.059
10        스웨덴 SEK   128.72   131.87   125.57   130.00   127.44  0.108
11         호주 AUD   831.94   848.32   815.56   840.25   823.63  0.695
12       뉴질랜드 NZD   783.33   798.76   767.90   791.16   775.50  0.654
13         체코 CZK    50.55    54.84    46.01    51.10    50.00  0.042
14         칠레 CLP     1.49     1.60     1.38     0.00     0.00  0.001
15         터키 TRY   174.43     0.00     0.00   176.34   172.52  0.146
16         몽골 MNT     0.42     0.00     0.00     0.00     0.00  0.000
17       이스라엘 ILS   348.50   383.35   320.62     0.00     0.00  0.291
18        덴마크 DKK   181.00   185.43   176.57   182.81   179.19  0.151
19       노르웨이 NOK   126.57   129.67   123.47   127.83   125.31  0.106
20    사우디아라비아 SAR   319.19   339.29   297.17   322.38   316.00  0.267
21       쿠웨이트 KWD  3889.86  4142.70  3578.68  3928.75  3850.97  3.249
22        바레인 BHD  3170.82  3373.75  2917.16  3202.52  3139.12  2.648
23     아랍에미리트 AED   325.96   343.88   303.47   329.21   322.71  0.272
24        요르단 JOD  1688.72  1839.01  1553.63     0.00     0.00  1.410
25        이집트 EGP    74.36     0.00     0.00     0.00     0.00  0.062
26         태국 THB    38.46    40.38    36.16    38.84    38.08  0.032
27       싱가포르 SGD   859.36   876.46   842.26   867.95   850.77  0.718
28      말레이시아 MYR   279.58   297.19   258.90     0.00   276.79  0.234
29  인도네시아 IDR 100     8.30     8.88     7.47     8.38     8.22  0.007
30        카타르 QAR   328.84     0.00     0.00     0.00     0.00  0.275
31      카자흐스탄 KZT     2.94     0.00     0.00     0.00     0.00  0.003
32       브루나이 BND   858.28   892.61   806.79     0.00     0.00  0.717
33         인도 INR    16.04     0.00     0.00     0.00     0.00  0.013
34       파키스탄 PKR     7.14     0.00     0.00     0.00     0.00  0.006
35      방글라데시 BDT    14.11     0.00     0.00     0.00     0.00  0.012
36        필리핀 PHP    24.16    26.57    22.18    24.40    23.92  0.020
37        멕시코 MXN    53.51    58.86    49.02    54.04    52.98  0.045
38        브라질 BRL   225.29   248.26   207.27     0.00   222.59  0.188
39    베트남 VND 100     5.16     5.76     4.56     5.21     5.11  0.004
40  남아프리카 공화국 ZAR    70.31    74.52    64.69    71.15    69.47  0.059
41        러시아 RUB    16.78    17.95    14.94    16.94    16.62  0.014
42        헝가리 HUF     3.81     4.16     3.51     3.85     3.77  0.003
43        폴란드 PLN   302.18   326.35   278.01   305.50   298.86  0.252

In [7]:
# 인덱스 지정
df = df.set_index('통화명') # 원본에 적용되는지 확인하기
df

                 매매기준율   현찰-사실때   현찰-파실때   송금-보낼때   송금-받을때  미화환산율
통화명
미국 USD         1197.30  1218.25  1176.35  1209.00  1185.60  1.000
유럽연합 EUR       1348.40  1375.23  1321.57  1361.88  1334.92  1.126
일본 JPY (100엔)  1112.68  1132.15  1093.21  1123.58  1101.78  0.929
중국 CNY          169.43   177.90   160.96   171.12   167.74  0.142
홍콩 HKD          154.49   157.53   151.45   156.03   152.95  0.129
대만 TWD           40.64    45.96    37.80     0.00     0.00  0.034
영국 GBP         1494.11  1523.54  1464.68  1509.05  1479.17  1.248
오만 OMR         3110.03  3386.82  2923.43     0.00     0.00  2.598
캐나다 CAD         883.45   900.85   866.05   892.28   874.62  0.738
스위스 CHF        1268.19  1293.17  1243.21  1280.87  1255.51  1.059
스웨덴 SEK         128.72   131.87   125.57   130.00   127.44  0.108
호주 AUD          831.94   848.32   815.56   840.25   823.63  0.695
뉴질랜드 NZD        783.33   798.76   767.90   791.16   775.50  0.654
체코 CZK           50.55    54.84    46.01    51.10    50.00  0.042
칠레 CLP            1.49     1.60     1.38     0.00     0.00  0.001
터키 TRY          174.43     0.00     0.00   176.34   172.52  0.146
몽골 MNT            0.42     0.00     0.00     0.00     0.00  0.000
이스라엘 ILS        348.50   383.35   320.62     0.00     0.00  0.291
덴마크 DKK         181.00   185.43   176.57   182.81   179.19  0.151
노르웨이 NOK        126.57   129.67   123.47   127.83   125.31  0.106
사우디아라비아 SAR     319.19   339.29   297.17   322.38   316.00  0.267
쿠웨이트 KWD       3889.86  4142.70  3578.68  3928.75  3850.97  3.249
바레인 BHD        3170.82  3373.75  2917.16  3202.52  3139.12  2.648
아랍에미리트 AED      325.96   343.88   303.47   329.21   322.71  0.272
요르단 JOD        1688.72  1839.01  1553.63     0.00     0.00  1.410
이집트 EGP          74.36     0.00     0.00     0.00     0.00  0.062
태국 THB           38.46    40.38    36.16    38.84    38.08  0.032
싱가포르 SGD        859.36   876.46   842.26   867.95   850.77  0.718
말레이시아 MYR       279.58   297.19   258.90     0.00   276.79  0.234
인도네시아 IDR 100     8.30     8.88     7.47     8.38     8.22  0.007
카타르 QAR         328.84     0.00     0.00     0.00     0.00  0.275
카자흐스탄 KZT         2.94     0.00     0.00     0.00     0.00  0.003
브루나이 BND        858.28   892.61   806.79     0.00     0.00  0.717
인도 INR           16.04     0.00     0.00     0.00     0.00  0.013
파키스탄 PKR          7.14     0.00     0.00     0.00     0.00  0.006
방글라데시 BDT        14.11     0.00     0.00     0.00     0.00  0.012
필리핀 PHP          24.16    26.57    22.18    24.40    23.92  0.020
멕시코 MXN          53.51    58.86    49.02    54.04    52.98  0.045
브라질 BRL         225.29   248.26   207.27     0.00   222.59  0.188
베트남 VND 100       5.16     5.76     4.56     5.21     5.11  0.004
남아프리카 공화국 ZAR    70.31    74.52    64.69    71.15    69.47  0.059
러시아 RUB          16.78    17.95    14.94    16.94    16.62  0.014
헝가리 HUF           3.81     4.16     3.51     3.85     3.77  0.003
폴란드 PLN         302.18   326.35   278.01   305.50   298.86  0.252

In [10]:
# (3) 엑셀로 데이타셋 보내기 
#   - 엑셀에서 활성화된(선택된) 시트로 보내짐
xw.view(df, xw.sheets.active)

In [11]:
# (4) 엑셀에서 가져오기(엑셀이 열려있어야만 가져옴)
xw.Range('a1:a7').value # a1~a7까지 가지고 오겠다.

['통화명', '미국 USD', '유럽연합 EUR', '일본 JPY (100엔)', '중국 CNY', '홍콩 HKD', '대만 TWD']